export const DISABLE_SAVE_POINT_TUTORIAL = 0x133;
export const DISABLE_CHOCOBO_TUTORIAL = 0x134;
export const VICKS_BROKE_WHELK_GATE = 0x12c;
export const NARSHE_GUARDS_SAW_TERRA_ON_BRIDGE = 0x12d;
export const TERRA_FELL_HOLE_NARSHE = 0x12e;
export const MET_ARVIS = 0x001; //characters no longer ride mtek armor in mines when set
export const DEFEATED_WHELK = 0x135;
export const NAMED_EDGAR = 0x004;
export const NAMED_SABIN = 0x005;
export const PRISON_DOOR_OPEN_FIGARO_CASTLE = 0x2b7;
export const MET_KEFKA_FIGARO_CASTLE = 0x006;
export const FIRST_NOISE_FIGARO_CAVE = 0x0ae;
export const SECOND_NOISE_FIGARO_CAVE = 0x0af;
export const THIRD_NOISE_FIGARO_CAVE = 0x0b0;
export const DEFEATED_TUNNEL_ARMOR = 0x0b1; //custom, used to be south figaro cave recovery spring
export const SAW_SHADOW_WALKING_TO_CAFE_SOUTH_FIGARO = 0x00a;
export const NAMED_SHADOW = 0x00b;
export const SAW_VARGAS_SHADOW1 = 0x00d;
export const SAW_VARGAS_SHADOW2 = 0x00e;
export const SAW_VARGAS_SHADOW3 = 0x00f;
export const DEFEATED_VARGAS = 0x010;
export const MET_BANON = 0x011;
export const GOT_GENJI_GLOVES_OR_GAUNTLET = 0x017;
export const RODE_RAFT_FIRST_TIME_LETE_RIVER = 0x019;
export const FOUGHT_ULTROS_LETE_RIVER = 0x01a;
export const RODE_RAFT_LETE_RIVER = 0x257;
export const WOUND_THE_CLOCK_SOUTH_FIGARO = 0x10d;
export const CELES_LOCKE_ESCAPED_SOUTH_FIGARO = 0x01b;
export const NAMED_CELES = 0x01c;
export const FREED_CELES = 0x01d;
export const FINISHED_LOCKE_SCENARIO = 0x01e;
export const NARSHE_SECRET_ENTRANCE_ACCESS = 0x020;
export const FINISHED_NARSHE_CHECKPOINT = 0x2d8; //custom, used to be narshe checkpoint explanation
export const FINISHED_TERRA_SCENARIO = 0x021;
export const SAW_SHADOW_DREAM1 = 0x024;
export const SAW_SHADOW_DREAM2 = 0x026;
export const SAW_SHADOW_DREAM3 = 0x027;
export const SAW_SHADOW_DREAM4 = 0x028;
export const RECRUITED_SHADOW_GAU_FATHER_HOUSE = 0x162;
export const CYAN_FOUND_POISONED_KING_DOMA = 0x031;
export const CYAN_FOUND_POISONED_FAMILY_DOMA = 0x032;
export const FINISHED_DOMA_WOB = 0x040; //custom
export const GENERAL_LEO_IMPERIAL_CAMP = 0x02b;
export const BRIDGE_BLOCKED_IMPERIAL_CAMP = 0x02c;
export const CHASING_KEFKA1_IMPERIAL_CAMP = 0x02d;
export const CHASING_KEFKA2_IMPERIAL_CAMP = 0x02e;
export const CHASING_KEFKA3_IMPERIAL_CAMP = 0x02f;
export const FINISHED_CHASING_KEFKA_IMPERIAL_CAMP = 0x155;
export const FINISHED_IMPERIAL_CAMP = 0x037;
export const LUMP_CHEST_DOOR_GHOST_PHANTOM_TRAIN = 0x180; //used for both door ghost in wob and lump of metal chest in wor
export const GOT_PHANTOM_TRAIN_REWARD = 0x192; //custom, used to be phantom forest recovery spring
export const FOUND_PHANTOM_TRAIN = 0x038;
export const STOPPED_PHANTOM_TRAIN = 0x03a;
export const DEFEATED_PHANTOM_TRAIN = 0x03b;
export const NAMED_GAU = 0x03f;
export const FOUND_DIVING_HELMET = 0x041;
export const FINISHED_SABIN_SCENARIO = 0x044;
export const FIGHTING_KEFKA_NARSHE_WOB = 0x132;
export const FINISHED_NARSHE_BATTLE = 0x046;
export const RECRUITED_SHADOW_KOHLINGEN = 0x18e;
export const CAN_LEARN_BUM_RUSH = 0x04b; //custom, set when all other blitzes learned or bum rush last disabled
export const LEARNED_BUM_RUSH = 0x2af;
export const GOT_SERPENT_TRENCH_REWARD = 0x050; //custom
export const SET_ZOZO_CLOCK = 0x51;
export const GOT_ZOZO_REWARD = 0x052; //custom
export const SAW_OPERA_OVERTURE = 0x055;
export const READY_CELES_OPERA_SCENE = 0x056;
export const BEGAN_OPERA_DISRUPTION = 0x110;
export const FINISHED_OPERA_PERFORMANCE = 0x111;
export const SAW_OPERA_DUEL_SCENE = 0x2ba;
export const OPERA_MAP_MODIFIED1 = 0x057;
export const FOUND_ULTROS_LETTER_OPERA = 0x58;
export const OPERA_MAP_MODIFIED2 = 0x059;
export const OPERA_MAP_MODIFIED3 = 0x05a;
export const FINISHED_OPERA_DISRUPTION = 0x05b; //custom
export const SETZER_ABDUCTED_CELES = 0x05c;
export const TOSSED_CELES_SETZER_COIN = 0x05d;
export const DEFEATED_NINJA_CAVE_TO_SEALED_GATE = 0x075; //custom
export const TERRA_AGREED_TO_OPEN_SEALED_GATE = 0x076;
export const DEFEATED_NUMBER_024 = 0x05f; //custom, used to be saw kefka throw ifrit/shiva in trash
export const DEFEATED_IFRIT_SHIVA_MAGITEK_FACTORY = 0x060;
export const GOT_IFRIT_SHIVA = 0x061;
export const TALKED_TO_IFRIT_MAGITEK_FACTORY = 0x272;
export const TALKED_TO_SHIVA_MAGITEK_FACTORY = 0x274;
export const DISABLE_HOOK_MAGITEK_FACTORY = 0x273;
export const RODE_MINE_CART_MAGITEK_FACTORY = 0x069;
export const MET_SETZER_AFTER_MAGITEK_FACTORY = 0x06a; //locke/celes not required in airship changing room after set
export const DEFEATED_CRANES = 0x06b;
export const SAW_MADUIN_DIE = 0x070; //enables lone wolf
export const ESPERS_CRASHED_AIRSHIP = 0x242; //allows entry to imperial base without terra
export const FINISHED_GESTAHL_DINNER = 0x07d;
export const MET_STRAGO_RELM = 0x08d;
export const DEFEATED_FLAME_EATER = 0x090;
export const DEFEATED_ULTROS_ESPER_MOUNTAIN = 0x095;
export const ESPER_MOUNTAIN_GATED = 0x097; //custom, if true relm won't appear and ultros battle won't happen, previously used for statues found
export const ESPER_MOUNTAIN_ACCESSIBLE = 0x098;
export const FOUND_ESPERS_ESPER_MOUNTAIN = 0x099;
export const DEFEATED_KEFKA_THAMASA = 0x09b;
export const LEO_BURIED_THAMASA = 0x09c;
export const FINISHED_THAMASA_KEFKA = 0x09d;
export const CONTINENT_IS_FLOATING = 0x09e;
export const LEARNED_TO_FLY_AIRSHIP = 0x16f;
export const AIRSHIP_VISIBLE = 0x1b9;
export const AIRSHIP_FLYING = 0x246;
export const GOT_FALCON = 0x0cd;
export const WON_AN_AUCTION = 0x166; //custom
export const AUCTION_BOUGHT_ESPER1 = 0x16c; //normally zoneseek
export const AUCTION_BOUGHT_ESPER2 = 0x16d; //normally golem
export const WON_A_COLISEUM_MATCH = 0x1ef; //custom, used to be shadow available at coliseum
export const BOUGHT_ESPER_TZEN = 0x27c; //normally sraphim
export const RECRUITED_SHADOW_FLOATING_CONTINENT = 0x02a;
export const DEFEATED_ATMAWEAPON = 0x0a1; //custom
export const DEFEATED_ATMA = 0x0a2; //custom
export const LEFT_SHADOW_FLOATING_CONTINENT = 0x0a3;
export const IN_WOR = 0x0a4;
export const FINISHED_FLOATING_CONTINENT = 0x0a5; //custom
export const STARTED_FEEDING_CID = 0x0b2; //custom, previously found cid dead
export const CID_SURVIVED = 0x0b3;
export const CID_DIED = 0x0b4;
export const FINISHED_FEEDING_CID = 0x0b9; //custom
export const BOARDED_CRIMSON_ROBBERS_BOAT_NIKEAH = 0x0ac;
export const DEFEATED_TENTACLES_FIGARO = 0x0c6;
export const LIGHT_JUDGEMENT_TZEN = 0x27d;
export const FINISHED_COLLAPSING_HOUSE = 0x28a;
export const HELPED_INJURED_LAD = 0x28d;
export const DOGS_BARKED_MOBLIZ_WOR = 0x28e;
export const MET_TERRA_WOR = 0x28f;
export const SAW_MOBLIZ_LIGHT_OF_JUDGEMENT_SCENE = 0x290;
export const FOUGHT_PHUNBABA1 = 0x291;
export const GOT_FENRIR = 0x2d7;
export const KATARIN_PREGNANT = 0x0be;
export const CHOSE_RAGNAROK_ESPER = 0x0b5; //custom
export const GOT_RAGNAROK = 0x0b6;
export const GOT_BOTH_REWARDS_WEAPON_SHOP = 0x0b7; //custom
export const CHASING_LONE_WOLF1 = 0x239;
export const CHASING_LONE_WOLF7 = 0x23f;
export const GOT_BOTH_REWARDS_LONE_WOLF = 0x241;
export const MET_LONE_WOLF_WOR = 0x29b;
export const RECRUITED_MOG_WOB = 0x29f;
export const RECRUITED_UMARO_WOR = 0x07e;
export const DARYL_TOMB_TURTLE1_MOVED = 0x2b4;
export const DARYL_TOMB_TURTLE2_MOVED = 0x2b6;
export const DEFEATED_DULLAHAN = 0x2b2;
export const RUST_RID_FOR_SALE = 0x298;
export const GOT_RUST_RID = 0x1db;
export const FOUND_CYAN_MT_ZOZO = 0x0d1; //custom
export const FINISHED_MT_ZOZO = 0x0d2;
export const DEFEATED_SR_BEHEMOTH = 0x199;
export const FOUND_DREAM_STOOGE1 = 0x189;
export const FOUND_DREAM_STOOGE2 = 0x18b;
export const FOUND_INTERCEPTOR_VELDT_CAVE_WOR = 0x195;
export const DEFEATED_CHADARNOOK = 0x253;
export const FOUND_EBOTS_ROCK = 0x19a;
export const MET_EBOTS_ROCK_CHEST = 0x19b;
export const DEFEATED_HIDON = 0x19c;
export const RECRUITED_GOGO_WOR = 0x0d4;
export const DEFEATED_STOOGES = 0x0d8;
export const FINISHED_DOMA_WOR = 0x0da;
export const GOT_ALEXANDR = 0x0db;
export const DEFEATED_MAGIMASTER = 0x2db;
export const RECRUITED_STRAGO_FANATICS_TOWER = 0x0ba;
export const DEFEATED_DOOM_GAZE = 0x2a1; //custom
export const RECRUITED_LOCKE_PHOENIX_CAVE = 0x0d7;
export const RECRUITED_TERRA_MOBLIZ = 0x0bf;
export const GOT_TRITOCH = 0x29e;
export const GOT_RAIDEN = 0x2dd;
export const FOUND_ANCIENT_CASTLE = 0x2df;
export const GOT_ODIN = 0x0c8;
export const SUPLEXED_TRAIN = 0x2b0; //custom, previously unused but set in nikeah entrance event
export const DEFEATED_NARSHE_DRAGON = 0x11a; //custom
export const DEFEATED_MT_ZOZO_DRAGON = 0x11b; //custom
export const DEFEATED_OPERA_HOUSE_DRAGON = 0x11c; //custom
export const DEFEATED_KEFKA_TOWER_DRAGON_G = 0x11d; //custom, gold dragon location
export const DEFEATED_KEFKA_TOWER_DRAGON_S = 0x11e; //custom, skull dragon location
export const DEFEATED_ANCIENT_CASTLE_DRAGON = 0x11f; //custom
export const DEFEATED_PHOENIX_CAVE_DRAGON = 0x120; //custom
export const DEFEATED_FANATICS_TOWER_DRAGON = 0x121; //custom
export const LEFT_WEIGHT_PUSHED_KEFKA_TOWER = 0x063;
export const RIGHT_WEIGHT_PUSHED_KEFKA_TOWER = 0x064;
export const WEST_PATH_BLOCKED_KEFKA_TOWER = 0x065; //path to doom in switch room
export const EAST_PATH_BLOCKED_KEFKA_TOWER = 0x066; //path to goddess in switch room
export const NORTH_PATH_OPEN_KEFKA_TOWER = 0x067; //path to guardian in switch room
export const SOUTH_PATH_OPEN_KEFKA_TOWER = 0x071; //path to balcony in switch room
export const CENTER_DOOR_KEFKA_TOWER = 0x080; //center door in weights room
export const LEFT_RIGHT_DOORS_KEFKA_TOWER = 0x0d0; //doors to doom/goddess opened on balcony
export const UNLOCKED_KT_SKIP = 0x093; //custom
export const UNLOCKED_FINAL_KEFKA = 0x094; //custom
export const SIEGFRIED_LUMP_OF_METAL_CHESTS = 0x187; //set after siegfried chest in phantom train and lump of metal chest in cyan's dream
export const VELDT_WORLD_MUSIC = 0x1bb;
export const VELDT_REWARD_OBTAINED = 0x1bc; //custom
export const DISABLE_SPRINT = 0x1c1;
export const DISABLE_MENU_ACCESS = 0x1c2;
export const TEMP_SONG_OVERRIDE = 0x1cc;
export const ENABLE_Y_PARTY_SWITCHING = 0x1ce;
export const ALWAYS_CLEAR = 0x176; //this event_bit is always clear, used for branching
